# -*- coding: utf-8 -*-
"""HackerRankQuiz

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wacy3hdE6sSSE2qqTQJN6-UxZbq5JSv5
"""

## FizzBuzz

def FizzBuzz(n):
    for i in n:
        if i % 3 == 0 and i % 5 == 0:
            print("FizzBuzz")
        elif i % 3 == 0:
            print("Fizz")
        elif i % 5 == 0:
            print("Buzz")
        else: print(i)

FizzBuzz(range(1,101))

FizzBuzz([1,2,3,4,5,6])

