# -*- coding: utf-8 -*-
"""BC12 Intro Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12vTP9WRUWWrqGdW1hDlPPW0X_970qi1F

#**Intro to Python Programming**

We learn 5 concepts + 1 OOP

- Variable & Calculation
- Data Type
- Data Structure
- Control Flow
- Function

# **Variable & Calculation**
"""

1+1

1+1
2*2

print(1+1)
print(2*2)

## print เพื่อแสดงผลทุกบรรทัด
print(100/2)
print(100//2)

## // หรือ floor division จะตัดเศษหายไป
## แต่ถ้าตัวหารมีทศนิยม ผลลัพธ์ก็จะมีทศนิยมต่อให้ //
print(3//2)
print(3//2.0)

## % หรือ modulo แสดงผลเศษ
5%2

## variable
x = 100
y = 200
print(x+y)

## naming variables
income =50000
expense = 36000
saving = income - expense
print(saving)

## snake case naming
income_y2025 = 65000

## remove variables
del saving

"""# **Data Types**
- int (จำนวนเต็ม)
- float (ทศนิยม)
- str (ตัวอักษร)
- bool (logic)
"""

name = "Toy"
text = "I'm loving Mcdonalds"
age = 28
fav_lang = "Python"
movie_lover = True # False

print(name, text, age, fav_lang, movie_lover)

type(age)

## type hint
name: int = "Noparuj"
type(name)

weight: int = 36
gpa: float = 3.8

## convert type
str(100)

int(False)

bool(1)

bool(0)

## f-string
name = "Tor"
age = 28
lang = "SQL"

text = f"Hi! my name is {name} and I am {age} years old. My fav lang is {lang}."

print(text)

"""# **Data Structures**
* list
* tuple
* dictionary
* set

### LIST is Mutalble
"""

## Shopping list
shop_list = ["egg", "milk", "bread", "butter"]

## check length of list
len(shop_list)

## index starts with 0
shop_list[0]

## slice items in a list
shop_list[0:2] #มาแค่ 0-1

## slice items til the end
shop_list[0:]

## list can contain multiple data types
Tor = ["Tor", 27, "BKK", 3.8, True] #ทำได้แต่ไม่ควรทำ

Tor[0:]

## nested list
brothers = [
    ["Tor",1998],
    ["Ton", 1996],
    ["Third", 2001]
    ]

brothers[1][1]

brothers[2][0]

"""

## Function vs. Method

```python
#function
print("Hi")

# method is a function for specific object(class)
object.method()"""

len(shop_list) #function

## method คือ function เฉพาะ
## ตัวอย่าง list methods = function ที่ใช้ได้กับ list เท่านั้น

shop_list.append("carrot")
shop_list

## remove last item
shop_list.pop()
shop_list

## insert item at the index we weant
shop_list.insert(2, "apple")
shop_list

## remove apple
shop_list.remove("apple")
shop_list

## string method
text = "a duck walks into a bar"

text.upper()

"""## Mutable vs. Immutable
* mutable = can change/transform e.g. `list` `dict` `set`
* immutable = cannot change/transform e.g. `str` `tuple`
"""

## list of my friends (mutable)
friends = ["bam", "poom", "mark"]

friends.append("ken")

friends

## string (immutable)
text = "a duck walks into a bar."
text = text.upper() ##ต้อง assign ค่าใหม่ แต่ mutable ไม่ต้องทำ

text

## lower case
text = text.lower()

text

## immutable
lang = "Ri"
lang[-1] = "B" ##ไม่ผ่าน อัพเดทค่าข้างในตัวแปรเดิมไม่ได้



new_lang = "C" + lang[1:] ## immutable ต้องประกาศตัวแปรใหม่
new_lang

shop_list.append("duck")

## mutable = can change
shop_list[0] = "juice"
shop_list[1] = "meat"
shop_list

## string method
text

text = text.replace("duck", "chicken")

text

text.count("chicken")

text = ".......hello...."
text = text.strip(".")

text

## split text
text = "I like chicken"
split_text = text.split(" ")

split_text

## join text
" ".join(split_text)

"""### TUPLE is immutable"""

my_tup = ()

type(my_tup)

type(shop_list)

books = ("help with work", "strong body", "best health")

books

books[0]

books[1]

## tuple unpacking
x, y, z = (100, 200, 300)
print(x+y+z)

"""### DICTIONARY is mutable

```python
{key: value}
```
"""

movie = {
    "title": "The Matrix",
    "release_year": 1999,
    "Director": "someone",
    "rating": {"imdb": 8.6,
               "rotten": 9.0
               },
    "cast": ["A", "B", "C"]
}

movie ##json format

movie["title"] = "Men"
movie["release_year"] = 2000
movie

movie["rev"] = 1000
movie

del movie["rev"]

movie

## dictionary method
## key, items, values
movie.keys()

movie.values()

movie.items()

titles = list(movie.keys())
titles

## convert data structure
## list(), tuple(), dict(), set()

list_a = [100,200,300]
tuple(list_a)

##update value in dictionary
movie["cast"][0] = "Tor"
movie

"""### SET is mutable
unique values in a set
"""

colors = ["red", "blue", "blue", "red"]

## del duplicate
set_colors = set(colors)

set_colors

books = {"book1", "book2", "book3"}
type(books)

set_colors.add("pink")
set_colors.add("green")
set_colors

set_colors.remove("pink")

"""# **Control Flow**
* if
* for
* while
"""

# if
score = 82
if score >= 80:
    print("pass")
else:
    print("fail")

## multiple grades รันจากบนลงล่าง
score = 50
if score >= 80:
    print("A")
elif score >= 70:
    print("B")
elif score >= 60:
    print("C")
else:
    print("D")

## get input
username = input("What's your username: ")
age = int(input ("How old are you: "))

print(age)
type(age)

## multiple conditions
## night club
has_id = True
age_over_18 = False
vip_customer = False

if has_id and (age_over_18 or vip_customer):
    print("Welcome to the club.")
else:
    print("Please come next time.")

## for & while
items = ["bag", "pen", "gum"]

for item in items:
    if item == "bag":
        print("My Bag")
    else:
        print(item)

## ทำ uppercase ยาวเกิน
result = []

for item in items:
    result.append(item.upper())
print(result)

## list comprehension (R ทำไม่ได้)
[item.upper() for item in items]

## while
while True:
    user_input = input("Continue: Y/N? ")
    if user_input == "N":
        print("Bye!")
        break
    else:
        print("Run!")

## while another e.g.
count = 0
while count < 5:
    print("test")
    count += 1

"""# **Function**
```python
def function_name():
    pass
```
"""

## create 1st function
def greeting(name):
    """
    say hi to everyone
    """
    print(f"Hi {name}!")

greeting("Tor")

greeting

## function can take inputs
greeting("Jane")

## new function cube()
def cube(base, power):
    return base**power

result = cube(5, 4) ##เอาค่า returnไปเป็น variable ได้ 625
print(result)

## function can return multiple values
## using tuple unpacking
def random_fun(base):
    return base**2, base**3, base**4

x, y, z = random_fun(5)
print(x,y,z, x+y+z)

## function is "reusable"

## chatbot HW
def chat():
    print("Hi there!")
    oders = {"hawaian": 0, "cheese": 0, "seafood": 0}
    while True:
        user_name = input("Username: ")
        print(f"Welcome to our restaurant Mr.{user_name}.")

        if user_input == "Check bill":
            ## calculate bill
            print("Thank you very much!")
            break

