# -*- coding: utf-8 -*-
"""Python for DA 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ja2mq8R0Pnvq9hJINrY-CALERo8Q296P

# **Essential Concepts in Python**
* lambda
* map, filter
* import module
* regex
* numpy + pandas
* json
* Bonus - Web Scraping
* Bonus - Debug

# Lambda
anonymous function ไร้ชื่อ

lambda arguments: expression

ใช้สร้าง Function ให้จบใน 1 บรรทัด /ไว้ใช้ร่วมกับ Map, Filter
"""

## Create a new function in python
def hi():
    print("hi")

hi()

def add_two_nums(a,b):
    return a+b

add_two_nums(5,2)

## lambda
test = lambda x: print(x)

test(100)

add_two = lambda num: print(num+2)

add_two(2)

add_two(7)

test = lambda a,b: a+b

test(1,2)

test2 = lambda name, fav_food: f"{name} loves {fav_food}."

test2("tor","egg")

"""# Map, Filter

ใช้ avoid for loop
"""

## iterable (adj)
scores = [82,78,81,66,50]

## for loop ปกติ
for score in scores:
    if score >= 80:
        print("pass")
    else:
        print("fail")

## map เตรียม function ต้องใช้ return
def grading(score):
    if score >= 80:
        return "pass"
    else:
        return "fail"

## map
list(map(grading,scores))

## add 5 to scores ปกติ
new_scores = []
for score in scores:
    new_scores.append(score+5)
print(new_scores)

## add 5 to scores + map + lambda
list(map(lambda x: x+5, scores))

## filter score > 80 ปกติ
students_score_over_80 = []
for score in scores:
    if score >= 80:
        students_score_over_80.append(score)
print(students_score_over_80)

## filter
list(filter(lambda x: x>=80, scores))

scores2 = [("toy", 80), ("jane", 75), ("jin", 92)]
## filter score>=80
list(filter(lambda x: x[1]>=80, scores2))

"""# Module/Library"""

## standard python modules
import random

fruits = ["apple", "orange", "banana", "grape", "lychee"]

for i in range(5):
    random.seed(42) ## lock random
    print(random.choice(fruits))

random.randint(10000,99999)

## hw: class ATM
import random

class ATM:
    def __init__(self, name, balance):
        self.name = name
        self.balance = balance

    def __str__(self):
        return f"Account owner: {self.name}\nAccount balance: {self.balance}"

    def get_otp(self):
        otp = random.randint(10000, 99999)
        return f"Your OTP: {otp}"

my_account = ATM("tor", 100)

print(my_account)

my_account.get_otp()

"""# REGEX"""

import re
text = "a duck duck costs $44 usd per duck"
re.search("duck",text) #แสดงผล d ลำดับที่ 2 และหลัง k ลำดับที่ 6

text[2:6]

re.findall("duck", text)

re.findall("[0-9]{2}",text)

"""# Numpy & Pandas

numpy = numerical python = matrix/ computing

All statistic function in numpy

(DA ไม่ค่อยได้ใช้)
"""

## magic command to install new library/ module
## จริงๆ google colab numpy มีอยู่แล้ว
!pip install numpy

!pip list

import random
nums = []

for i in range(10):
    nums.append(random.randint(100,999))
print(nums)

sum(nums) / len(nums)

min(nums)

import numpy as np

print(np.sum(nums),
    np.mean(nums),
    np.std(nums),
    np.median(nums),
    np.var(nums))

## change nums list to array
## array == vector in R
nums = np.array(nums)
type(nums)

## numpy method
print(nums.sum(),
      nums.std(),
      nums.mean(),
      nums.min(),
      nums.max())

## import pandas + numpy
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "name": ["tor", "ton", "third"],
    "income": [100,200,300]
})

df["income"].median()

"""# JSON

json = JavaScript Object Notation (Key Value Pair)

"""

## working with json
profile = {
    "name": "Tor",
    "age": 26,
    "movies": ["Oldman", "Men"],
    "city": "BKK"
}

type(profile)

## import json
import json

## write json file
with open ("profile.json","w") as file:
    json.dump(profile, file)

!cat profile.json

## read json file
with open("profile.json", "r") as file:
    data = json.load(file)

data

data["movies"][1]

"""# Bonus - Simple Web Scraping

Beautiful soup มีอยู่แล้วใน Colab

-> แต่ใช้ Gazpacho เขียนง่ายกว่า

ดึงได้แต่ Static Web (Dynamic Web ที่ใช้ JavaScript ต้องใช้ตัวอื่น)
"""

!pip install gazpacho

## import library(modules)
import requests
from gazpacho import Soup ## soup เป็น Function ใน gazpacho

url = "https://raw.githubusercontent.com/toyeiei/python-test-bc12/refs/heads/main/index.html"

## get request
response = requests.get(url)

response.status_code

web = Soup(response.text)

for li in web.find("li"):
    print(li.strip())

url = "https://datarockie.com"

resp = requests.get(url)
resp.status_code

datarockie = Soup(resp.text)

datarockie.find("h1").strip()

for h2 in datarockie.find("h2"):
    print(h2.strip())

"""# Bonus - Debug

## Debug Function
"""

def add(a, b):
    print(a)   # ดูว่า a คืออะไร
    print(b)   # ดูว่า b คืออะไร
    return a + b

add(3,5)

"""## Debug IF/ELSE"""

def check_score(score):
    if score >= 50:
        print("PASS branch")
        return "Pass"
    else:
        print("FAIL branch")
        return "Fail"

check_score(40)

"""## Debug For Loop"""

def sum_list(nums):
    total = 0
    for n in nums:
        print("current n:", n)
        total += n
    print("final total:", total)
    return total

nums= [40,20]

sum_list(nums)

"""## Debug Check Type"""

def multiply(a, b):
    print(type(a), type(b))
    return a * b

multiply(4,3)

"""## Debug Error Spot"""

def process(nums):
    print("start")
    total = sum(nums)
    print("after sum")
    avg = total / len(nums)
    print("after avg")
    return avg

process(nums)

