# -*- coding: utf-8 -*-
"""Python for DA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cvWh9zNSd_ilnYOYo0O8IjZAAdUYwpqA

# **Python for DA**
* OOP (Object Oriented Programming
* Read and Write File
* Context Manager
* Handle Error
* Pandas & Numpy (on demand)
* Request API
"""

from google.colab import drive
drive.mount('/content/drive')

"""# OOP  (Object Oriented Programming)
การสอนให้ Computer รู้จัก Object

Concept เหมือน Cookie Cutter
"""

class Dog: ##ตัวแรก Capital
    def __init__(self, name, species, age) -> None: ##double underscore / dunder
        self.name = name
        self.species = species
        self.age = age
    def bark(self):
        print(f"{self.name} is barking")
    def birthday(self):
        self.age += 1
        print(f"{self.name} is {self.age}")
    pass

dog1 = Dog("Milo", "Pom", 3)
dog2 = Dog("Milk", "Husky", 4)

print(f"{dog1.name} is {dog1.species}")
print(f"{dog2.name} is {dog2.species}")

dog1.bark()

dog1.birthday()
dog2.birthday()

"""# องค์ประกอบ OOP
* attributes: name, species,  age
* methods: function bark() birthday()
"""

class ATM:
    def __init__(self, username, bank, balance):
        self.username = username
        self.bank = bank
        self.balance = balance

    def __str__(self): ##ใช้ return function print()
        return f"Hi {self.username}! I'm {self.bank}'s ATM Machine."

    def check_balance(self):
        print(f"Your balance is {self.balance} THB.")
    def deposit(self, amount):

        self.balance += amount
        print(f"Deposit {amount} THB success.")

tor = ATM("Tor", "K-bank", 100)

print(f"Welcome to {tor.username}'s {tor.bank} account.")

tor.check_balance()

tor.deposit(3000)

print(tor)

"""# **Super Class**

สาย Software ได้ใช้ในการขาย Base Class

สาย DA ไม่ค่อยได้ใช้


"""

class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

## extension / build on top
class Employee(Person):
    def __init__(self, name, age, company):
        super().__init__(name, age) ##super refer to Person
        self.company = company

    def greeting(self):
        print("Hi!")

person1 = Person("tor", 27)

person2 = Employee("May", 28, "SCB")

person2.greeting()

"""# Read File

## Magic command to run Terminal
"""

!pwd #magic command to run Terminal

!ls

"""## Try Except Block

ใช้แก้ปัญหา error เพราะ Python 1 error ทำให้ code ใช้ไม่ได้เลย
"""

try:
    result = 1/0
except:
    print("error here!")

"""## Read CSV File"""

!cat hotel.csv

## read file
import csv ##ควร import บนสุด / csv เป็น standard python

try:
    file = open("hotel.csv", "r") ## r=read/ w=write/ a=append

    ## module.function()
    data = csv.reader(file)

    for row in data:
        print(row)

    file.close()
except:
    print("file not found")
finally:
    print("read file success")

"""# Context Manager

ช่วยในการลดขั้นตอน Read/Close File

## Standard python
ใช้ csv. Reader
"""

read_data = []

with open("hotel.csv", "r") as file:
    data = csv.reader(file)
    for row in data:
        read_data.append(row)

read_data

read_data[0]

read_data[1:]

## for loop to calculate avg.price_per_night
prices = []

for row in read_data[1:]:
    prices.append(int(row[4]))

print(f"Avg. prices: {sum(prices)/len(prices)}")

"""## Modern python
ใช้ pandas module ช่วยในการทำงาน df
"""

## modern python
import pandas as pd
df = pd.read_csv("hotel.csv")
df.head()

df.price_per_night.mean()

"""#Write File

##Standard python
"""

import csv

# write file + context Manager
head = ["id", "name", "city"]
body = [
    [1, "CU", "Bangkok"],
    [2, "LSE", "London"],
    [3, "Reading", "Reading"]
]

with open("school.csv","w") as file:
    writer = csv.writer(file)
    writer.writerow(head)
    writer.writerows(body)

!ls

!cat school.csv

"""## Modern python"""

import pandas as pd
df = pd.read_csv("school.csv")
df.head()

df.to_csv("school2.csv")

!ls

!cat school2.csv

## read data from internet
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/penguins.csv"

import pandas as pd
df_penguin = pd.read_csv(url)

df_penguin.head()

## select column
df_penguin[["species", "island", "body_mass_g"]].head(10)

## filter rows
## จัดบรรทัด python ด้วย \
df_penguin[["species", "island", "body_mass_g"]] \
    .query("species == 'Adelie' and island == 'Torgersen'") \
    .head(10)

df_penguin[df_penguin['body_mass_g'] >= 4500][["species", "island", "body_mass_g"]].head(10)

"""# Requests API

How to get data via API the easy way
API คือ standard Protocol ที่ใช้รับ-ส่งข้อมูลผ่าน Computer ด้วยการวิ่งไปที่ API Endpoint

Local -> Server (Get Request)
* Complete = 200 ## status code
* Site not found = 404
* Server error = 503

Server -> Local (Response)
"""

import requests
url = "https://swapi.info/api/people/1"

response = requests.get(url)

response.json()["name"]

## for loop
import requests
import time


character = []
for i in range(5):
    url = f"https://swapi.info/api/people/{i+1}"
    response = requests.get(url)
    response_json = response.json()
    data = [response_json["name"],
            response_json["height"],
            response_json["mass"]
            ]
    character.append(data)
    print(f"Success: {i+1}")
    time.sleep(1)

print(character)

import pandas as pd
starwars = pd.DataFrame(character, columns=["name", "height", "mass"])

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/Python_for_DA.py

!jupyter nbconvert --to script Python_for_DA.ipynb

